const gyanDatabase = [
  // DAY 1: Foundations
  { id: 1, cat: "Polity", title: "Article 324", body: "Grants the Election Commission power to direct and control elections.", color: "#3498db" },
  { id: 2, cat: "History", title: "1905 Partition", body: "Bengal was partitioned by Lord Curzon; led to the Swadeshi Movement.", color: "#e67e22" },
  { id: 3, cat: "Science", title: "Blood pH", body: "Human blood is slightly basic, ranging between 7.35 and 7.45.", color: "#e74c3c" },
  { id: 4, cat: "Economy", title: "Repo Rate", body: "The interest rate at which RBI lends money to commercial banks.", color: "#2ecc71" },
  { id: 5, cat: "Geography", title: "IST Meridian", body: "India's time is based on 82.5°E, passing through Mirzapur, UP.", color: "#9b59b6" },
  { id: 6, cat: "Motivation", title: "Deep Work", body: "Cal Newport's concept: Focus without distraction on a cognitively demanding task.", color: "#34495e" },
  { id: 7, cat: "Math", title: "Prime Numbers", body: "2 is the only even prime number; all others are odd.", color: "#1abc9c" },
  { id: 8, cat: "Awareness", title: "Cyber Safety", body: "Never click 'Shortened Links' in SMS claiming you won a lottery.", color: "#c0392b" },
  { id: 9, cat: "Quiz", title: "DPSP Source", body: "Directive Principles of State Policy were borrowed from Ireland.", color: "#16a085" },
  { id: 10, cat: "CA 2026", title: "Hydrogen Train", body: "India's first H-train trials began on Jind-Sonipat route in 2026.", color: "#27ae60" },

  // DAY 2: Executive & Environment
  { id: 11, cat: "Polity", title: "Article 74", body: "Provides for a Council of Ministers with the PM to advise the President.", color: "#2980b9" },
  { id: 12, cat: "History", title: "Quit India", body: "Started in 1942; Mahatma Gandhi gave the 'Do or Die' call.", color: "#d35400" },
  { id: 13, cat: "Science", title: "Vitamin C", body: "Also called Ascorbic Acid; its deficiency causes Scurvy.", color: "#f1c40f" },
  { id: 14, cat: "Economy", title: "GST Council", body: "A constitutional body chaired by the Union Finance Minister.", color: "#7f8c8d" },
  { id: 15, cat: "Geography", title: "Nilgiris", body: "The 'Blue Mountains' where the Western and Eastern Ghats meet.", color: "#2ecc71" },
  { id: 16, cat: "Logic", title: "Syllogism", body: "A form of reasoning where a conclusion is drawn from two premises.", color: "#8e44ad" },
  { id: 17, cat: "Did You Know?", title: "Zero", body: "Indian mathematician Aryabhata used zero as a placeholder/digit.", color: "#34495e" },
  { id: 18, cat: "CA 2026", title: "DGCA Chief", body: "Vir Vikram Yadav is currently leading the aviation regulatory body.", color: "#16a085" },
  { id: 19, cat: "Awareness", title: "UPI Safety", body: "Reminder: You do NOT need a PIN to RECEIVE money via UPI.", color: "#c0392b" },
  { id: 20, cat: "Quiz", title: "Largest State", body: "Rajasthan is India's largest state by total land area.", color: "#8e44ad" },

  // DAY 3: Rights & Revolts
  { id: 21, cat: "Polity", title: "Article 21", body: "Right to Protection of Life and Personal Liberty (Fundamental Right).", color: "#3498db" },
  { id: 22, cat: "History", title: "1857 Revolt", body: "Began in Meerut; Mangal Pandey is a key figure of this uprising.", color: "#e67e22" },
  { id: 23, cat: "Science", title: "Photosynthesis", body: "Plants use sunlight to convert CO2 and water into glucose.", color: "#27ae60" },
  { id: 24, cat: "Economy", title: "Blue Revolution", body: "Refers to the rapid increase in fish production and aquaculture.", color: "#2980b9" },
  { id: 25, cat: "Geography", title: "Majuli Island", body: "The world's largest river island, located in the Brahmaputra, Assam.", color: "#9b59b6" },
  { id: 26, cat: "Motivation", title: "Eat the Frog", body: "Do your hardest, most important task first thing in the morning.", color: "#34495e" },
  { id: 27, cat: "Math", title: "Fibonacci", body: "Sequence where each number is the sum of the two preceding ones.", color: "#1abc9c" },
  { id: 28, cat: "Awareness", title: "Phishing", body: "Fraudulent emails that look official to steal your bank passwords.", color: "#c0392b" },
  { id: 29, cat: "Quiz", title: "Silicon Valley", body: "Bengaluru is widely known as the Silicon Valley of India.", color: "#16a085" },
  { id: 30, cat: "Science", title: "Inertia", body: "Newton's 1st Law: An object stays at rest unless acted on by a force.", color: "#e74c3c" },

  // DAY 4: Amendments & Rivers
  { id: 31, cat: "Polity", title: "42nd Amendment", body: "Known as the 'Mini Constitution'; added Socialist and Secular to Preamble.", color: "#2980b9" },
  { id: 32, cat: "History", title: "Indus Valley", body: "Harappa and Mohenjo-daro were the first planned urban cities.", color: "#d35400" },
  { id: 33, cat: "Science", title: "Sound Speed", body: "Sound travels fastest in solids and slowest in gases (cannot travel in vacuum).", color: "#f39c12" },
  { id: 34, cat: "Economy", title: "Inflation", body: "A general increase in prices and fall in the purchasing value of money.", color: "#c0392b" },
  { id: 35, cat: "Geography", title: "Godavari", body: "Known as 'Dakshin Ganga', it is the second longest river in India.", color: "#27ae60" },
  { id: 36, cat: "Motivation", title: "Pomodoro", body: "Work for 25 minutes, then take a 5-minute break to stay fresh.", color: "#34495e" },
  { id: 37, cat: "Did You Know?", title: "Shampoo", body: "The concept of shampooing originated in India using herbs/berries.", color: "#7f8c8d" },
  { id: 38, cat: "CA 2026", title: "Gaganyaan", body: "ISRO's 2026 goal for the first manned space flight mission.", color: "#16a085" },
  { id: 39, cat: "Awareness", title: "Blue Light", body: "Screens emit blue light that can disrupt your sleep cycle (Melatonin).", color: "#2c3e50" },
  { id: 40, cat: "Quiz", title: "High Court", body: "The Calcutta High Court is the oldest High Court in India.", color: "#8e44ad" },

  // DAY 5: Local Government & Space
  { id: 41, cat: "Polity", title: "73rd Amendment", body: "Gave constitutional status to Panchayati Raj institutions.", color: "#3498db" },
  { id: 42, cat: "History", title: "Ashoka's Edicts", body: "Inscriptions on pillars/rocks promoting Dhamma (righteousness).", color: "#e67e22" },
  { id: 43, cat: "Science", title: "Escape Velocity", body: "On Earth, it is approx 11.2 km/s to leave the gravitational pull.", color: "#9b59b6" },
  { id: 44, cat: "Economy", title: "White Revolution", body: "Led by Verghese Kurien (Amul) to increase milk production.", color: "#f1c40f" },
  { id: 45, cat: "Geography", title: "Karakoram", body: "Range containing K2 (Godwin-Austen), the 2nd highest peak.", color: "#34495e" },
  { id: 46, cat: "Logic", title: "Odd One Out", body: "Identifying a member of a set that is different from others.", color: "#1abc9c" },
  { id: 47, cat: "Math", title: "Pythagoras", body: "In a right triangle: a² + b² = c² (Hypotenuse calculation).", color: "#2ecc71" },
  { id: 48, cat: "Awareness", title: "Incognito", body: "Incognito mode hides history from the device, but NOT from the ISP.", color: "#c0392b" },
  { id: 49, cat: "Quiz", title: "Tiger State", body: "Madhya Pradesh holds the record for the highest tiger population.", color: "#16a085" },
  { id: 50, cat: "CA 2026", title: "UCC Bill", body: "Gujarat recently moved toward implementing the Uniform Civil Code.", color: "#d35400" },

  // DAY 6: Parliament & Energy
  { id: 51, cat: "Polity", title: "Article 110", body: "Defines 'Money Bills'; only the Speaker decides if a bill is a Money Bill.", color: "#2980b9" },
  { id: 52, cat: "History", title: "Dandi March", body: "1930 Salt Satyagraha; a major non-violent protest against salt tax.", color: "#e67e22" },
  { id: 53, cat: "Science", title: "Refraction", body: "Bending of light as it passes from one medium to another.", color: "#1abc9c" },
  { id: 54, cat: "Economy", title: "FDI", body: "Foreign Direct Investment: investment made by a firm into another country.", color: "#27ae60" },
  { id: 55, cat: "Geography", title: "Standard Time", body: "IST is 5 hours and 30 minutes ahead of GMT (UTC +5:30).", color: "#9b59b6" },
  { id: 56, cat: "Motivation", title: "80/20 Rule", body: "Pareto Principle: 80% of results come from 20% of effort.", color: "#34495e" },
  { id: 57, cat: "Did You Know?", title: "Chess", body: "The game of Chess originated in India (formerly called Chaturanga).", color: "#d35400" },
  { id: 58, cat: "CA 2026", title: "Solar Power", body: "India targets 500GW non-fossil fuel energy capacity by 2030.", color: "#f1c40f" },
  { id: 59, cat: "Awareness", title: "Dark Mode", body: "Reduces eye strain in low light and saves battery on OLED screens.", color: "#2c3e50" },
  { id: 60, cat: "Quiz", title: "Smallest State", body: "Goa is the smallest state in India by total area.", color: "#16a085" },

  // DAY 7: Judiciary & Biology
  { id: 61, cat: "Polity", title: "Article 124", body: "Establishment and Constitution of the Supreme Court of India.", color: "#3498db" },
  { id: 62, cat: "History", title: "Magadha", body: "Ancient Indian kingdom; Bimbisara and Ajatashatru were its rulers.", color: "#e67e22" },
  { id: 63, cat: "Science", title: "Mitochondria", body: "Known as the 'Powerhouse of the Cell'; produces ATP energy.", color: "#e74c3c" },
  { id: 64, cat: "Economy", title: "Direct Tax", body: "Taxes paid directly to the government (Income Tax, Corp Tax).", color: "#7f8c8d" },
  { id: 65, cat: "Geography", title: "Sundarbans", body: "The world's largest mangrove forest, home to Royal Bengal Tigers.", color: "#27ae60" },
  { id: 66, cat: "Math", title: "Unit Digit", body: "The last digit of 2^4 is 6. Useful in solving complex powers.", color: "#1abc9c" },
  { id: 67, cat: "Motivation", title: "Growth Mindset", body: "Believing abilities can be developed through hard work.", color: "#34495e" },
  { id: 68, cat: "Awareness", title: "VPN", body: "Virtual Private Network: encrypts your internet traffic for privacy.", color: "#c0392b" },
  { id: 69, cat: "Quiz", title: "Yellow River", body: "The Huang He is called the 'Sorrow of China' due to floods.", color: "#16a085" },
  { id: 70, cat: "CA 2026", title: "Semiconductors", body: "India’s project 'ISM' aims to become a global hub for chip making.", color: "#d35400" },

  // DAY 8: Duties & Climate
  { id: 71, cat: "Polity", title: "Art. 51A", body: "Fundamental Duties: added by 42nd Amendment upon Swaran Singh's rec.", color: "#2980b9" },
  { id: 72, cat: "History", title: "Battle of Plassey", body: "1757: British victory over Nawab Siraj-ud-Daulah (led by Clive).", color: "#d35400" },
  { id: 73, cat: "Science", title: "Ozone Layer", body: "Located in the Stratosphere; protects us from harmful UV rays.", color: "#16a085" },
  { id: 74, cat: "Economy", title: "Capital Market", body: "Where long-term financial instruments like shares are traded.", color: "#2ecc71" },
  { id: 75, cat: "Geography", title: "Great Circles", body: "The Equator is the largest great circle on Earth.", color: "#9b59b6" },
  { id: 76, cat: "Logic", title: "Coding-Decoding", body: "A test of logic where words are converted to secret symbols/letters.", color: "#8e44ad" },
  { id: 77, cat: "Did You Know?", title: "First Univ.", body: "Takshashila is considered one of the world's first universities.", color: "#7f8c8d" },
  { id: 78, cat: "CA 2026", title: "G20", body: "India continues to influence global policy following its 2023 presidency.", color: "#34495e" },
  { id: 79, cat: "Awareness", title: "2-Factor Auth", body: "Always use 2FA for Gmail/Social media to prevent hacking.", color: "#c0392b" },
  { id: 80, cat: "Quiz", title: "First Citizen", body: "The President of India is considered the 'First Citizen'.", color: "#3498db" },

  // DAY 9: Rights & Cells
  { id: 81, cat: "Polity", title: "Article 32", body: "Right to Constitutional Remedies: 'Heart and Soul' of Constitution.", color: "#3498db" },
  { id: 82, cat: "History", title: "Ashoka's Dhamma", body: "A code of moral conduct rather than a specific religion.", color: "#e67e22" },
  { id: 83, cat: "Science", title: "Red Blood Cells", body: "Carry oxygen via Hemoglobin; they do not have a nucleus.", color: "#e74c3c" },
  { id: 84, cat: "Economy", title: "Bull Market", body: "When stock prices are rising or expected to rise.", color: "#2ecc71" },
  { id: 85, cat: "Geography", title: "Palk Strait", body: "The narrow strip of water separating India from Sri Lanka.", color: "#9b59b6" },
  { id: 86, cat: "Motivation", title: "Flow State", body: "Being fully immersed and energized in what you are doing.", color: "#34495e" },
  { id: 87, cat: "Math", title: "Rational Numbers", body: "Any number that can be expressed as a fraction p/q.", color: "#1abc9c" },
  { id: 88, cat: "Awareness", title: "Social Media", body: "Doomscrolling (endless scrolling) increases anxiety/stress.", color: "#c0392b" },
  { id: 89, cat: "Quiz", title: "Golden Fiber", body: "Jute is known as the 'Golden Fiber' of India.", color: "#16a085" },
  { id: 90, cat: "CA 2026", title: "Digital Rupee", body: "RBI’s CBDC (Central Bank Digital Currency) expanding nationwide.", color: "#27ae60" },

  // DAY 10: Revision & Governance
  { id: 91, cat: "Polity", title: "Veto Power", body: "The President can withhold assent to a bill (Absolute, Suspensive, Pocket).", color: "#2980b9" },
  { id: 92, cat: "History", title: "Tashkent Declaration", body: "Peace agreement between India & Pakistan (1966) after 1965 war.", color: "#d35400" },
  { id: 93, cat: "Science", title: "Newton's 3rd Law", body: "For every action, there is an equal and opposite reaction.", color: "#f39c12" },
  { id: 94, cat: "Economy", title: "Microfinance", body: "Financial services for poor individuals who lack access to banks.", color: "#7f8c8d" },
  { id: 95, cat: "Geography", title: "Narmada River", body: "One of the few major west-flowing rivers in India; flows through a rift valley.", color: "#27ae60" },
  { id: 96, cat: "Logic", title: "Series Completion", body: "Finding the next number in a sequence based on a pattern.", color: "#8e44ad" },
  { id: 97, cat: "Did You Know?", title: "Number System", body: "The modern decimal system was developed in India (Hindu-Arabic).", color: "#7f8c8d" },
  { id: 98, cat: "CA 2026", title: "S&P Outlook", body: "Projected 7% growth for India, making it the fastest-growing major economy.", color: "#34495e" },
  { id: 99, cat: "Awareness", title: "Posture", body: "Keep your spine straight while studying to avoid long-term back pain.", color: "#c0392b" },
  { id: 100, cat: "Quiz", title: "NITI Aayog", body: "Replaced the Planning Commission; PM is the ex-officio Chairman.", color: "#16a085" },


// DAY 11: Space & Judiciary
  { id: 101, cat: "Polity", title: "Article 131", body: "Original jurisdiction of Supreme Court (disputes between Center & States).", color: "#3498db" },
  { id: 102, cat: "History", title: "Tashkent Pact", body: "1966 peace agreement signed between Lal Bahadur Shastri and Ayub Khan.", color: "#e67e22" },
  { id: 103, cat: "Science", title: "Refraction", body: "Bending of light as it passes from one medium to another (e.g., air to water).", color: "#1abc9c" },
  { id: 104, cat: "Economy", title: "Antariksh Fund", body: "India's dedicated Space Venture Capital fund established in 2026.", color: "#7f8c8d" },
  { id: 105, cat: "Geography", title: "Majuli Island", body: "The world's largest river island, located in the Brahmaputra, Assam.", color: "#2ecc71" },
  { id: 106, cat: "Logic", title: "Blood Relations", body: "Identifying relationships based on generational trees and gender cues.", color: "#8e44ad" },
  { id: 107, cat: "CA 2026", title: "Naxal-Free India", body: "On March 31, 2026, India officially declared its 'Naxal-free' status.", color: "#c0392b" },
  { id: 108, cat: "Motivation", title: "Pomo-doro", body: "Focus for 25 mins, rest for 5. It trains your brain to stay sharp.", color: "#34495e" },
  { id: 109, cat: "Quiz", title: "Oldest HC", body: "The Calcutta High Court (est. 1862) is the oldest in India.", color: "#16a085" },
  { id: 110, cat: "Awareness", title: "Phishing", body: "Fake links that steal data. Always check the URL before entering passwords.", color: "#d35400" },

  // DAY 12: Finance & Freedom
  { id: 111, cat: "Polity", title: "Article 280", body: "Finance Commission: A body that decides tax sharing between Center/States.", color: "#2980b9" },
  { id: 112, cat: "History", title: "Dandi March", body: "1930 Salt Satyagraha: Gandhiji walked 240 miles to break the salt law.", color: "#d35400" },
  { id: 113, cat: "Science", title: "Vitamin D", body: "Synthesized by the skin via UV rays; essential for Calcium absorption.", color: "#f1c40f" },
  { id: 114, cat: "Economy", title: "Repo Rate", body: "Current April 2026 rate is key for controlling market inflation.", color: "#27ae60" },
  { id: 115, cat: "Geography", title: "Karakoram Pass", body: "Highest pass on the ancient silk route between India and China.", color: "#9b59b6" },
  { id: 116, cat: "Math", title: "Average Speed", body: "2xy / (x+y) — used when a person covers two equal distances at speeds x and y.", color: "#1abc9c" },
  { id: 117, cat: "Did You Know?", title: "Shampoo", body: "Derived from 'Champo' (Sanskrit); the concept originated in India.", color: "#7f8c8d" },
  { id: 118, cat: "CA 2026", title: "Bhavasagara", body: "India's 1st National Repository for Deep-Sea Fauna (Kochi, 2026).", color: "#34495e" },
  { id: 119, cat: "Awareness", title: "SIM-Binding", body: "New 2026 OTT rule: Apps must link to active SIMs to curb cybercrime.", color: "#c0392b" },
  { id: 120, cat: "Quiz", title: "Silicon Valley", body: "Bengaluru is the tech hub known as India's Silicon Valley.", color: "#16a085" },

  // DAY 13: Environment & Evolution
  { id: 121, cat: "Polity", title: "Article 360", body: "Financial Emergency: Has never been proclaimed in India yet.", color: "#3498db" },
  { id: 122, cat: "History", title: "Ashoka's Dhamma", body: "A moral code of conduct focused on peace, tolerance, and respect.", color: "#e67e22" },
  { id: 123, cat: "Science", title: "Photosynthesis", body: "Plants convert Solar energy into Chemical energy using Chlorophyll.", color: "#2ecc71" },
  { id: 124, cat: "Economy", title: "GST Council", body: "A constitutional body for tax rates, headed by the Finance Minister.", color: "#f39c12" },
  { id: 125, cat: "Geography", title: "Sundarbans", body: "World's largest delta; home to the Royal Bengal Tiger.", color: "#27ae60" },
  { id: 126, cat: "Logic", title: "Syllogism", body: "Method to find conclusions like: 'All A are B, some B are C'.", color: "#8e44ad" },
  { id: 127, cat: "Math", title: "Divisibility 11", body: "(Sum of odd digits) - (Sum of even digits) = 0 or multiple of 11.", color: "#1abc9c" },
  { id: 128, cat: "CA 2026", title: "SDG Dashboard", body: "MoSPI launched a new unified dashboard to track India's progress in 2026.", color: "#2980b9" },
  { id: 129, cat: "Awareness", title: "Dark Mode", body: "Reduces blue light strain and saves battery on OLED screens.", color: "#2c3e50" },
  { id: 130, cat: "Quiz", title: "Tiger State", body: "Madhya Pradesh has the highest tiger population in India.", color: "#d35400" },

  // DAY 14: Culture & Constitutional Bodies
  { id: 131, cat: "Polity", title: "Article 315", body: "Constitutional provision for UPSC and State PSCs.", color: "#3498db" },
  { id: 132, cat: "History", title: "Vedic Age", body: "Rigveda is the oldest Veda; focuses on prayers to Nature Gods.", color: "#e67e22" },
  { id: 133, cat: "Science", title: "Mitochondria", body: "The powerhouse of the cell; it produces ATP (Energy currency).", color: "#e74c3c" },
  { id: 134, cat: "Economy", title: "Blue Revolution", body: "Refers to the rapid growth in fish production and aquaculture.", color: "#3498db" },
  { id: 135, cat: "Geography", title: "Western Ghats", body: "A UNESCO heritage site and one of the world's 8 biodiversity hotspots.", color: "#2ecc71" },
  { id: 136, cat: "Motivation", title: "Atomic Habits", body: "James Clear: Getting 1% better daily makes you 37x better in a year.", color: "#34495e" },
  { id: 137, cat: "Did You Know?", title: "Chess", body: "The game originated in India, known as 'Chaturanga' in Sanskrit.", color: "#d35400" },
  { id: 138, cat: "CA 2026", title: "Coal-to-Gas", body: "Odisha got India's 1st indigenous coal-to-ammonium nitrate project (2026).", color: "#7f8c8d" },
  { id: 139, cat: "Awareness", title: "VPN", body: "Virtual Private Network: Encrypts data to protect your IP address.", color: "#c0392b" },
  { id: 140, cat: "Quiz", title: "Largest Delta", body: "Ganga-Brahmaputra Delta is the largest in the world.", color: "#16a085" },

  // DAY 15: Amendments & Astronomy
  { id: 141, cat: "Polity", title: "42nd Amendment", body: "Known as 'Mini Constitution'; added 'Socialist' & 'Secular' to Preamble.", color: "#2980b9" },
  { id: 142, cat: "History", title: "Indus Valley", body: "Harappa was the 1st site discovered (1921) by Daya Ram Sahni.", color: "#d35400" },
  { id: 143, cat: "Science", title: "Escape Velocity", body: "11.2 km/s — Speed needed to leave Earth's gravity.", color: "#9b59b6" },
  { id: 144, cat: "Economy", title: "Bull vs Bear", body: "Bull: Market rising (optimistic). Bear: Market falling (pessimistic).", color: "#2ecc71" },
  { id: 145, cat: "Geography", title: "Kanchenjunga", body: "Highest mountain peak entirely within Indian territory.", color: "#27ae60" },
  { id: 146, cat: "Math", title: "Unit Digit 5", body: "Any power of a number ending in 5 always ends in 5.", color: "#1abc9c" },
  { id: 147, cat: "Motivation", title: "80/20 Rule", body: "Pareto Principle: 20% of your efforts bring 80% of your results.", color: "#34495e" },
  { id: 148, cat: "CA 2026", title: "Solar Goal", body: "India aiming for 500 GW of non-fossil fuel capacity by 2030.", color: "#f39c12" },
  { id: 149, cat: "Awareness", title: "Incognito", body: "Browsing 'Incognito' does NOT hide your data from your ISP or Employer.", color: "#c0392b" },
  { id: 150, cat: "Quiz", title: "First Citizen", body: "The President of India is called the First Citizen of the country.", color: "#3498db" },

  // DAY 16: Parliament & Particles
  { id: 151, cat: "Polity", title: "Article 110", body: "Definition of Money Bills. Speaker's decision on this is final.", color: "#3498db" },
  { id: 152, cat: "History", title: "Battle of Plassey", body: "1757: Robert Clive defeated Nawab Siraj-ud-Daulah (Start of British Rule).", color: "#e67e22" },
  { id: 153, cat: "Science", title: "Isotopes", body: "Atoms of same element with same atomic number but different mass.", color: "#1abc9c" },
  { id: 154, cat: "Economy", title: "FDI", body: "Foreign Direct Investment: Investment made into a firm located in India.", color: "#27ae60" },
  { id: 155, cat: "Geography", title: "Palk Strait", body: "The narrow sea dividing India and Sri Lanka.", color: "#9b59b6" },
  { id: 156, cat: "Logic", title: "Number Series", body: "Find the logic (Square, Cube, Diff) to find the next number.", color: "#8e44ad" },
  { id: 157, cat: "Did You Know?", title: "Shakuntala Devi", body: "The 'Human Computer' who could calculate 13-digit multiplication in seconds.", color: "#d35400" },
  { id: 158, cat: "CA 2026", title: "Green Card", body: "Uttarakhand launched fitness Green Cards for Char Dham vehicles (2026).", color: "#2ecc71" },
  { id: 159, cat: "Awareness", title: "2FA", body: "Two-Factor Authentication: The best way to prevent Gmail/X hacks.", color: "#c0392b" },
  { id: 160, cat: "Quiz", title: "Smallest State", body: "Goa is the smallest state in India by total area.", color: "#16a085" },

  // DAY 17: Local Govt & Biology
  { id: 161, cat: "Polity", title: "73rd Amendment", body: "Gave constitutional status to Panchayati Raj (Village Councils).", color: "#2980b9" },
  { id: 162, cat: "History", title: "Harsha Charita", body: "Biography of King Harshavardhana, written by Banabhatta.", color: "#d35400" },
  { id: 163, cat: "Science", title: "Red Blood Cells", body: "RBCs carry oxygen and do not have a nucleus (more room for Hemoglobin).", color: "#e74c3c" },
  { id: 164, cat: "Economy", title: "Direct Tax", body: "Taxes paid by the person on whom they are levied (e.g., Income Tax).", color: "#7f8c8d" },
  { id: 165, cat: "Geography", title: "Western Ghats", body: "A UNESCO biodiversity hotspot; starts from Tapi river in Gujarat.", color: "#2ecc71" },
  { id: 166, cat: "Math", title: "Percentage trick", body: "x% of y is the same as y% of x. Example: 4% of 50 = 50% of 4.", color: "#1abc9c" },
  { id: 167, cat: "Motivation", title: "Growth Mindset", body: "The belief that you can improve skills with effort and learning.", color: "#34495e" },
  { id: 168, cat: "CA 2026", title: "Army Vice Chief", body: "Lt Gen Dhiraj Seth assumed charge as 49th Vice Chief (April 2026).", color: "#16a085" },
  { id: 169, cat: "Awareness", title: "Post-Naxal Dev.", body: "2026 focus: Establishing schools/hospitals in former Red Corridor districts.", color: "#c0392b" },
  { id: 170, cat: "Quiz", title: "Daughter of Ganga", body: "River Yamuna is the largest tributary of the Ganga.", color: "#3498db" },

  // DAY 18: Duties & Climate
  { id: 171, cat: "Polity", title: "Article 51A", body: "Lists the 11 Fundamental Duties. (Based on Swaran Singh Committee).", color: "#3498db" },
  { id: 172, cat: "History", title: "Jallianwala Bagh", body: "1919: General Dyer ordered firing on a peaceful crowd in Amritsar.", color: "#e67e22" },
  { id: 173, cat: "Science", title: "Ozone Layer", body: "Found in Stratosphere; filters out harmful UV-B rays from the sun.", color: "#16a085" },
  { id: 174, cat: "Economy", title: "Inflation", body: "A general increase in price levels over time (CPI tracks this).", color: "#c0392b" },
  { id: 175, cat: "Geography", title: "Great Circles", body: "The Equator is the only latitude that is a great circle.", color: "#9b59b6" },
  { id: 176, cat: "Logic", title: "Analogy", body: "Comparing relationships, e.g., 'India : Delhi :: USA : ?' (Answer: D.C.).", color: "#8e44ad" },
  { id: 177, cat: "Did You Know?", title: "Nalanda", body: "One of the world's oldest residential universities (5th Century AD).", color: "#d35400" },
  { id: 178, cat: "CA 2026", title: "RBL Bank Stake", body: "RBI approved Emirates NBD’s 60% stake acquisition in RBL Bank (2026).", color: "#7f8c8d" },
  { id: 179, cat: "Awareness", title: "Blue Card", body: "Foreign cars now need 'Blue Cards' for eco-sensitive Himalayan zones (2026).", color: "#2ecc71" },
  { id: 180, cat: "Quiz", title: "National Anthem", body: "Written by Rabindranath Tagore; first sung in 1911 Calcutta session.", color: "#3498db" },

  // DAY 19: Rights & Cells
  { id: 181, cat: "Polity", title: "Article 32", body: "Right to Constitutional Remedies. Called the 'Heart and Soul' by Ambedkar.", color: "#3498db" },
  { id: 182, cat: "History", title: "Indus Dockyard", body: "Lothal (Gujarat) had the world's first artificial dockyard.", color: "#e67e22" },
  { id: 183, cat: "Science", title: "WBCs", body: "White Blood Cells: The 'Soldiers' of the body that fight infections.", color: "#e74c3c" },
  { id: 184, cat: "Economy", title: "Capital Market", body: "Where companies raise long-term funds by issuing shares/bonds.", color: "#2ecc71" },
  { id: 185, cat: "Geography", title: "Western vs Eastern", body: "Western Ghats are continuous; Eastern Ghats are broken by rivers.", color: "#9b59b6" },
  { id: 186, cat: "Motivation", title: "Flow State", body: "The state of mind where you are fully lost in your study work.", color: "#34495e" },
  { id: 187, cat: "Math", title: "Square of 25", body: "Multiplication trick: 2x3=6, then add 25 = 625.", color: "#1abc9c" },
  { id: 188, cat: "CA 2026", title: "Candidate 2026", body: "Praggnanandhaa made a strong start at the Candidates Chess tourney (2026).", color: "#16a085" },
  { id: 189, cat: "Awareness", title: "SWM Rules 2026", body: "New rules: Wet, Dry, Sanitary, and Special care waste segregation.", color: "#2ecc71" },
  { id: 190, cat: "Quiz", title: "Golden Fiber", body: "Jute is known as the Golden Fiber due to its high value.", color: "#16a085" },

  // DAY 20: Revision & Governance
  { id: 191, cat: "Polity", title: "NITI Aayog", body: "Replaced Planning Commission (2015); it is a 'Think Tank'.", color: "#2980b9" },
  { id: 192, cat: "History", title: "Mughal Empire", body: "Babur founded it in 1526 after the 1st Battle of Panipat.", color: "#d35400" },
  { id: 193, cat: "Science", title: "Newton's 3rd Law", body: "Every action has an equal and opposite reaction (Rocket launch).", color: "#f39c12" },
  { id: 194, cat: "Economy", title: "Gini Coefficient", body: "A measure of income inequality. 0 is perfect equality, 1 is total inequality.", color: "#7f8c8d" },
  { id: 195, cat: "Geography", title: "Narmada River", body: "One of the few west-flowing rivers that flow through a Rift Valley.", color: "#27ae60" },
  { id: 196, cat: "Logic", title: "Series Logic", body: "Always check for Square (+/-) constant or Prime number patterns.", color: "#8e44ad" },
  { id: 197, cat: "Did You Know?", title: "Number System", body: "Decimal system and Place value were created in India.", color: "#7f8c8d" },
  { id: 198, cat: "CA 2026", title: "Antariksh Startups", body: "Selected space startups to get investment from Antariksh Fund in FY2027.", color: "#34495e" },
  { id: 199, cat: "Awareness", title: "Posture", body: "Lower back support is key during long sittings to avoid sciatica.", color: "#c0392b" },
  { id: 200, cat: "Quiz", title: "First PM", body: "Jawaharlal Nehru was the longest-serving Prime Minister of India.", color: "#16a085" },

// DAY 21: International Relations & Space
  { id: 201, cat: "Polity", title: "Article 51", body: "Directive Principle: Promotion of international peace and security.", color: "#3498db" },
  { id: 202, cat: "History", title: "Non-Alignment", body: "NAM (1961): India's policy of not joining any major power blocs (US/USSR).", color: "#e67e22" },
  { id: 203, cat: "Science", title: "LUPEX 2026", body: "ISRO-JAXA joint mission in 2026 to explore the Moon's South Pole water.", color: "#1abc9c" },
  { id: 204, cat: "Economy", title: "Blue Economy", body: "Sustainable use of ocean resources for economic growth (2026 target).", color: "#2ecc71" },
  { id: 205, cat: "Geography", title: "Rohtang Pass", body: "High mountain pass on the eastern Pir Panjal Range; connects Kullu-Lahaul.", color: "#9b59b6" },
  { id: 206, cat: "Logic", title: "Directions", body: "Shadow trick: In the morning, a person's shadow is always to the West.", color: "#8e44ad" },
  { id: 207, cat: "CA 2026", title: "6G Testbed", body: "India successfully launched its 100th 6G R&D testbed in April 2026.", color: "#34495e" },
  { id: 208, cat: "Motivation", title: "Feynman Tech", body: "Explain a concept to a 5-year-old. If you can't, you don't know it.", color: "#d35400" },
  { id: 209, cat: "Quiz", title: "Oldest Veda", body: "Rigveda is the oldest of the four Vedas (written in Vedic Sanskrit).", color: "#16a085" },
  { id: 210, cat: "Awareness", title: "Juice Jacking", body: "2026 Alert: Avoid public USB charging stations; hackers can steal data.", color: "#c0392b" },

  // DAY 22: Rights & Rivers
  { id: 211, cat: "Polity", title: "Article 44", body: "Directive Principle: Implementation of a Uniform Civil Code (UCC).", color: "#2980b9" },
  { id: 212, cat: "History", title: "Civil Disobedience", body: "1930: Movement launched by breaking the salt law at Dandi.", color: "#d35400" },
  { id: 213, cat: "Science", title: "Heavier than Air", body: "Airplanes fly because of Bernoulli's principle: higher speed = lower pressure.", color: "#1abc9c" },
  { id: 214, cat: "Economy", title: "Nifty 50", body: "Index representing the weighted average of 50 Indian company stocks.", color: "#27ae60" },
  { id: 215, cat: "Geography", title: "Teesta River", body: "Tributary of Brahmaputra; vital water source for Sikkim and Bengal.", color: "#9b59b6" },
  { id: 216, cat: "Math", title: "Profit/Loss", body: "Profit % = (Profit/C.P.) * 100. Always calculate on Cost Price.", color: "#1abc9c" },
  { id: 217, cat: "Did You Know?", title: "Yoga Origin", body: "Yoga dates back 5,000 years to the Indus-Saraswati civilization.", color: "#7f8c8d" },
  { id: 218, cat: "CA 2026", title: "Bharat-AIR", body: "2026: India's first AI-driven air quality prediction system launched.", color: "#16a085" },
  { id: 119, cat: "Awareness", title: "Digital Will", body: "2026 Trend: Setting up 'Legacy Contacts' on social media for after death.", color: "#c0392b" },
  { id: 220, cat: "Quiz", title: "Ganga Origin", body: "Ganga originates as Bhagirathi from the Gangotri Glacier.", color: "#3498db" },

  // DAY 23: Environment & Local Bodies
  { id: 221, cat: "Polity", title: "74th Amendment", body: "Gave constitutional status to Urban Local Bodies (Municipalities).", color: "#3498db" },
  { id: 222, cat: "History", title: "Bhakti Movement", body: "Medieval movement focused on personal devotion to God (Kabir, Mirabai).", color: "#e67e22" },
  { id: 223, cat: "Science", title: "Greenhouse Gas", body: "Methane (CH4) is 25x more potent than CO2 in trapping heat.", color: "#2ecc71" },
  { id: 224, cat: "Economy", title: "FII", body: "Foreign Institutional Investors: funds that invest in Indian assets.", color: "#f39c12" },
  { id: 225, cat: "Geography", title: "Zoji La", body: "Pass connecting Srinagar to Leh; crucial for Himalayan logistics.", color: "#27ae60" },
  { id: 226, cat: "Logic", title: "Venn Diagrams", body: "Used to show relationships between sets (e.g., Cats, Dogs, Animals).", color: "#8e44ad" },
  { id: 227, cat: "Math", title: "Ratio Trick", body: "If A:B = 2:3 and B:C = 4:5, then A:B:C = 8:12:15.", color: "#1abc9c" },
  { id: 228, cat: "CA 2026", title: "Semicon India", body: "April 2026: India's 1st mega-semiconductor fab began production in Dholera.", color: "#2980b9" },
  { id: 229, cat: "Awareness", title: "RFID Tags", body: "How Fastag works: uses Radio Frequency to scan/deduct toll money.", color: "#2c3e50" },
  { id: 230, cat: "Quiz", title: "Pink City", body: "Jaipur is known as the Pink City because of its distinct architecture.", color: "#d35400" },

  // DAY 24: Culture & Bodies
  { id: 231, cat: "Polity", title: "CAG of India", body: "Article 148: Guardian of the public purse; audits all Govt spending.", color: "#3498db" },
  { id: 232, cat: "History", title: "Gupta Empire", body: "Known as the 'Golden Age' of India for art, science, and literature.", color: "#e67e22" },
  { id: 233, cat: "Science", title: "DNA", body: "Deoxyribonucleic Acid: The blueprint of life in a double-helix shape.", color: "#e74c3c" },
  { id: 234, cat: "Economy", title: "Primary Sector", body: "Activities using natural resources directly (Agriculture, Mining).", color: "#3498db" },
  { id: 235, cat: "Geography", title: "Nathu La", body: "Pass in Sikkim on the Indo-China border; reopened in 2006 for trade.", color: "#2ecc71" },
  { id: 236, cat: "Motivation", title: "Zeigarnik", body: "Your brain remembers unfinished tasks better. Start now, finish later.", color: "#34495e" },
  { id: 237, cat: "Did You Know?", title: "Snakes & Ladders", body: "Originated in India as 'Moksha Patam' to teach morality to kids.", color: "#d35400" },
  { id: 238, cat: "CA 2026", title: "INS Arighat", body: "2026: India's 2nd Arihant-class nuclear sub actively patrolling.", color: "#7f8c8d" },
  { id: 239, cat: "Awareness", title: "QR Fraud", body: "Warning: Scanning a QR code is ONLY for SNELLING money, not receiving.", color: "#c0392b" },
  { id: 240, cat: "Quiz", title: "Brahmaputra Name", body: "In Tibet, the Brahmaputra is known as the Tsangpo.", color: "#16a085" },

  // DAY 25: Amendments & Energy
  { id: 241, cat: "Polity", title: "61st Amendment", body: "Lowered the voting age from 21 to 18 years (1989).", color: "#2980b9" },
  { id: 242, cat: "History", title: "Mauryan Pillars", body: "Built by Ashoka to spread Dhamma; features the Lion Capital (Emblem).", color: "#d35400" },
  { id: 243, cat: "Science", title: "Nuclear Fusion", body: "The reaction powering the Sun: Hydrogen atoms join to form Helium.", color: "#9b59b6" },
  { id: 244, cat: "Economy", title: "Direct Tax", body: "Taxes like Income Tax that cannot be shifted to others.", color: "#2ecc71" },
  { id: 245, cat: "Geography", title: "Indira Point", body: "The southernmost point of India, located in the Nicobar Islands.", color: "#27ae60" },
  { id: 246, cat: "Math", title: "Unit Digit 0,1,6", body: "Any power of a number ending in 0, 1, 5, or 6 always ends in the same.", color: "#1abc9c" },
  { id: 247, cat: "Motivation", title: "Kaizen", body: "The Japanese philosophy of continuous, tiny improvements every day.", color: "#34495e" },
  { id: 248, cat: "CA 2026", title: "Digital Health", body: "April 2026: 95% of Indians now have an ABHA (Digital Health) ID.", color: "#f39c12" },
  { id: 249, cat: "Awareness", title: "Dark Patterns", body: "2026 law: Websites can't use trick designs to make you buy more.", color: "#c0392b" },
  { id: 250, cat: "Quiz", title: "Smallest Planet", body: "Mercury is the smallest planet in our solar system.", color: "#3498db" },

  // DAY 26: Parliament & Particles
  { id: 251, cat: "Polity", title: "Article 108", body: "Provision for Joint Sitting of both Houses of Parliament.", color: "#3498db" },
  { id: 252, cat: "History", title: "Battle of Haldighati", body: "1576: Fought between Maharana Pratap and the Mughal forces of Akbar.", color: "#e67e22" },
  { id: 253, cat: "Science", title: "Protons", body: "Positively charged particles in an atom's nucleus; discovered by Rutherford.", color: "#1abc9c" },
  { id: 254, cat: "Economy", title: "SDR", body: "Special Drawing Rights: International reserve asset created by the IMF.", color: "#27ae60" },
  { id: 255, cat: "Geography", title: "Tropic of Cancer", body: "Passes through 8 Indian states (Guj, Raj, MP, Chat, Jhar, WB, Tri, Miz).", color: "#9b59b6" },
  { id: 256, cat: "Logic", title: "Clock Logic", body: "Angle between hands at 3:00 is 90 degrees. Formula: |30h - 5.5m|.", color: "#8e44ad" },
  { id: 257, cat: "Did You Know?", title: "First Satellite", body: "Aryabhata (1975) was India's first satellite, launched by USSR.", color: "#d35400" },
  { id: 258, cat: "CA 2026", title: "Holo-Display", body: "2026: India's 1st holographic traffic signals tested in Bengaluru.", color: "#2ecc71" },
  { id: 259, cat: "Awareness", title: "Cookie Consent", body: "Reject 'Third-party' cookies to stop advertisers from tracking you.", color: "#c0392b" },
  { id: 260, cat: "Quiz", title: "Iron Man", body: "Sardar Vallabhbhai Patel is known as the Iron Man of India.", color: "#16a085" },

  // DAY 27: Bodies & Biology
  { id: 261, cat: "Polity", title: "Article 76", body: "Attorney General of India: The highest law officer in the country.", color: "#2980b9" },
  { id: 262, cat: "History", title: "Arya Samaj", body: "Founded by Swami Dayanand Saraswati in 1875 ('Go back to Vedas').", color: "#d35400" },
  { id: 263, cat: "Science", title: "Platelets", body: "Components in blood that help in clotting to stop bleeding.", color: "#e74c3c" },
  { id: 264, cat: "Economy", title: "GST Council", body: "Article 279A: Decides rates of GST; Union Finance Minister is Chair.", color: "#7f8c8d" },
  { id: 265, cat: "Geography", title: "Lakshadweep", body: "India's smallest UT; it is an archipelago of coral islands.", color: "#2ecc71" },
  { id: 266, cat: "Math", title: "Speed of Light", body: "Approx 300,000 km/s. In a vacuum, nothing travels faster.", color: "#1abc9c" },
  { id: 267, cat: "Motivation", title: "Pareto", body: "The 80/20 rule: 20% of your syllabus will give 80% of exam marks.", color: "#34495e" },
  { id: 268, cat: "CA 2026", title: "eVTOL", body: "2026: Trials for India's 1st Electric Flying Taxis began in Chennai.", color: "#16a085" },
  { id: 269, cat: "Awareness", title: "Deepfake Law", body: "2026: India passed the AI Accountability Act to stop deepfake crimes.", color: "#c0392b" },
  { id: 270, cat: "Quiz", title: "Red River", body: "The Brahmaputra is often called the Red River due to its silt.", color: "#3498db" },

  // DAY 28: Duties & Climate
  { id: 271, cat: "Polity", title: "Article 21A", body: "Right to Education: Free and compulsory education (6-14 years).", color: "#3498db" },
  { id: 272, cat: "History", title: "Swaraj", body: "Word popularized by Tilak: 'Swaraj is my birthright, I shall have it'.", color: "#e67e22" },
  { id: 273, cat: "Science", title: "Greenhouse Effect", body: "Warming of Earth due to heat trapped by gases like CO2 and CH4.", color: "#16a085" },
  { id: 274, cat: "Economy", title: "Laffer Curve", body: "Shows the relationship between tax rates and tax revenue.", color: "#c0392b" },
  { id: 275, cat: "Geography", title: "Standard Time", body: "IST is 5 hours and 30 mins ahead of GMT (Greenwich Mean Time).", color: "#9b59b6" },
  { id: 276, cat: "Logic", title: "Coding", body: "If CAT=3120, DOG=? (Answer: 4157 based on Alphabet position).", color: "#8e44ad" },
  { id: 277, cat: "Did You Know?", title: "First Printing", body: "First printing press in India was brought by Portuguese (Goa, 1556).", color: "#d35400" },
  { id: 278, cat: "CA 2026", title: "Green Bonds", body: "2026: India raised $10B via Green Bonds for renewable energy.", color: "#7f8c8d" },
  { id: 279, cat: "Awareness", title: "OLED Burn-in", body: "Keep brightness low on static screens to avoid permanent image ghosting.", color: "#2ecc71" },
  { id: 280, cat: "Quiz", title: "Missile Man", body: "Dr. A.P.J. Abdul Kalam is known as the Missile Man of India.", color: "#3498db" },

  // DAY 29: Rights & Planets
  { id: 281, cat: "Polity", title: "Article 368", body: "Grants Parliament the power to amend the Constitution.", color: "#3498db" },
  { id: 282, cat: "History", title: "Jainism", body: "Mahavira was the 24th Tirthankara; focused on Ahimsa (Non-violence).", color: "#e67e22" },
  { id: 283, cat: "Science", title: "Absolute Zero", body: "-273.15°C (0 Kelvin): The temperature where all particle motion stops.", color: "#e74c3c" },
  { id: 284, cat: "Economy", title: "Mixed Economy", body: "India's system: Co-existence of both Public and Private sectors.", color: "#2ecc71" },
  { id: 285, cat: "Geography", title: "Western Ghats", body: "Also known as Sahyadris; one of the world's 8 biodiversity hotspots.", color: "#9b59b6" },
  { id: 286, cat: "Motivation", title: "Sleep", body: "Your brain cleans itself (Glymphatic system) during 7-8 hours of sleep.", color: "#34495e" },
  { id: 287, cat: "Math", title: "LCM of Primes", body: "The LCM of any two prime numbers is simply their product (e.g., 3 & 7 is 21).", color: "#1abc9c" },
  { id: 288, cat: "CA 2026", title: "Antariksh-1", body: "2026: India launched its 1st private Space Station module 'Antariksh-1'.", color: "#16a085" },
  { id: 289, cat: "Awareness", title: "Smart Home", body: "Change default passwords on smart cameras to prevent hackers.", color: "#2ecc71" },
  { id: 290, cat: "Quiz", title: "Oldest Range", body: "Aravalli Range is the oldest fold mountain range in India.", color: "#16a085" },

  // DAY 30: Revision & Governance
  { id: 291, cat: "Polity", title: "Writ of Habeas Corpus", body: "Court order to produce a detained person to check if arrest is legal.", color: "#2980b9" },
  { id: 292, cat: "History", title: "Buddhist Council", body: "1st Council was held at Rajgriha after Buddha's death.", color: "#d35400" },
  { id: 293, cat: "Science", title: "Conductor", body: "Silver is the best conductor of electricity, followed by Copper.", color: "#f39c12" },
  { id: 294, cat: "Economy", title: "Repo Rate", body: "The rate at which RBI lends money to commercial banks.", color: "#7f8c8d" },
  { id: 295, cat: "Geography", title: "Indus River", body: "One of the longest rivers; originates near Mansarovar Lake, Tibet.", color: "#27ae60" },
  { id: 296, cat: "Logic", title: "Mirror Images", body: "Left becomes Right, Right becomes Left. Top/Bottom stay the same.", color: "#8e44ad" },
  { id: 297, cat: "Did You Know?", title: "First University", body: "Takshashila (600 BCE) is considered the world's 1st university.", color: "#7f8c8d" },
  { id: 298, cat: "CA 2026", title: "Ind-USA Pact", body: "2026: Major drone technology transfer agreement signed with USA.", color: "#34495e" },
  { id: 299, cat: "Awareness", title: "E-Waste 2026", body: "Donate old phones to certified recyclers; don't throw them in trash.", color: "#c0392b" },
  { id: 300, cat: "Quiz", title: "Largest Ocean", body: "The Pacific Ocean is the largest and deepest ocean on Earth.", color: "#16a085" },

// DAY 31: Medieval & Space Law
  { id: 301, cat: "Polity", title: "Article 262", body: "Adjudication of disputes relating to waters of inter-State rivers.", color: "#3498db" },
  { id: 302, cat: "History", title: "Iltutmish", body: "Real founder of Delhi Sultanate; introduced Silver Tanka & Copper Jital.", color: "#e67e22" },
  { id: 303, cat: "Science", title: "Black Holes", body: "Regions of spacetime where gravity is so strong that nothing, even light, can escape.", color: "#1abc9c" },
  { id: 304, cat: "Economy", title: "Blue Bonds", body: "2026: SEBI issued new guidelines for Blue Bonds to fund ocean-friendly projects.", color: "#2ecc71" },
  { id: 305, cat: "Geography", title: "Bomdi La", body: "Pass in Arunachal Pradesh connecting India with Lhasa, Tibet.", color: "#9b59b6" },
  { id: 306, cat: "Logic", title: "Seating", body: "In circular seating facing center: Left is Clockwise, Right is Anti-clockwise.", color: "#8e44ad" },
  { id: 307, cat: "CA 2026", title: "Space Law", body: "India passed the 'National Space Act 2026' to regulate private satellite launches.", color: "#34495e" },
  { id: 308, cat: "Motivation", title: "Pareto", body: "Identify the 20% of your syllabus that accounts for 80% of exam questions.", color: "#d35400" },
  { id: 309, cat: "Quiz", title: "Oldest Epic", body: "The Ramayana and Mahabharata are the world's longest and oldest epics.", color: "#16a085" },
  { id: 310, cat: "Awareness", title: "SIM Swap", body: "2026 Alert: If your phone loses signal suddenly, check for unauthorized SIM swaps.", color: "#c0392b" },

  // DAY 32: Rights & Resources
  { id: 311, cat: "Polity", title: "Article 338", body: "National Commission for Scheduled Castes (NCSC) constitutional provision.", color: "#2980b9" },
  { id: 312, cat: "History", title: "Alauddin Khilji", body: "Introduced 'Dagh' (branding horses) and 'Chehra' (descriptive roll of soldiers).", color: "#d35400" },
  { id: 313, cat: "Science", title: "Nuclear Fission", body: "Splitting of a heavy nucleus into lighter ones (used in Power Plants).", color: "#f1c40f" },
  { id: 314, cat: "Economy", title: "G-Secs", body: "Government Securities: Debt instruments issued by the RBI on behalf of the Govt.", color: "#27ae60" },
  { id: 315, cat: "Geography", title: "Chilika Lake", body: "Largest brackish water lagoon in India, located in Odisha.", color: "#9b59b6" },
  { id: 316, cat: "Math", title: "Ratio 2", body: "If a:b = 2:3, then 10a + 5b is solved by substituting a=2 and b=3.", color: "#1abc9c" },
  { id: 317, cat: "Did You Know?", title: "First Stamp", body: "The first postage stamp in India was the 'Scinde Dawk' issued in 1852.", color: "#7f8c8d" },
  { id: 318, cat: "CA 2026", title: "6G Launch", body: "PM announced India's first 6G hyper-speed network pilot in Delhi (April 2026).", color: "#16a085" },
  { id: 319, cat: "Awareness", title: "AI Voice", body: "2026 Scam: AI can mimic a family member's voice. Always use a 'Secret Word' to verify.", color: "#c0392b" },
  { id: 320, cat: "Quiz", title: "Largest Planet", body: "Jupiter is the largest planet; it has the shortest day in the solar system.", color: "#3498db" },

  // DAY 33: Finance & Environment
  { id: 321, cat: "Polity", title: "Article 243", body: "The basic constitutional article defining Panchayats and Municipalities.", color: "#3498db" },
  { id: 322, cat: "History", title: "Sufi Movement", body: "Emphasized love for God and service to humanity (Nizamuddin Auliya).", color: "#e67e22" },
  { id: 323, cat: "Science", title: "Coriolis Force", body: "Deflects winds to the right in Northern hemisphere (due to Earth's rotation).", color: "#2ecc71" },
  { id: 324, cat: "Economy", title: "Laffer Curve", body: "Shows that increasing tax rates beyond a point actually decreases revenue.", color: "#f39c12" },
  { id: 125, cat: "Geography", title: "Barren Island", body: "India's only active volcano, located in the Andaman Sea.", color: "#27ae60" },
  { id: 326, cat: "Logic", title: "Ranking", body: "If X is 10th from top and 15th from bottom, total people = 10 + 15 - 1.", color: "#8e44ad" },
  { id: 327, cat: "Math", title: "Compound Interest", body: "CI = P[(1 + r/100)^n - 1]. Known as the '8th wonder' for wealth growth.", color: "#1abc9c" },
  { id: 328, cat: "CA 2026", title: "Project Kusha", body: "India's long-range air defense system (LR-SAM) successfully tested in 2026.", color: "#2980b9" },
  { id: 329, cat: "Awareness", title: "Passkeys", body: "2026 Trend: Move from passwords to Passkeys (biometrics) for better security.", color: "#2c3e50" },
  { id: 330, cat: "Quiz", title: "Himalayas", body: "Fold mountains formed by the collision of Indian and Eurasian plates.", color: "#d35400" },

  // DAY 34: Bodies & Battles
  { id: 331, cat: "Polity", title: "Article 165", body: "Advocate General for the State: The state's counterpart to the Attorney General.", color: "#3498db" },
  { id: 332, cat: "History", title: "Battles of Tarain", body: "1191 & 1192: Fought between Prithviraj Chauhan and Muhammad Ghori.", color: "#e67e22" },
  { id: 333, cat: "Science", title: "Centripetal", body: "The force that keeps an object moving in a circle (e.g., Moon around Earth).", color: "#e74c3c" },
  { id: 334, cat: "Economy", title: "SEBI", body: "Statutory body established in 1992 to protect investors in securities market.", color: "#3498db" },
  { id: 335, cat: "Geography", title: "Palghat Gap", body: "A low mountain pass in the Western Ghats between Tamil Nadu and Kerala.", color: "#2ecc71" },
  { id: 336, cat: "Motivation", title: "Eisenhower", body: "Matrix: Divide tasks into Urgent, Important, and Not Urgent/Important.", color: "#34495e" },
  { id: 337, cat: "Did You Know?", title: "First Bridge", body: "The Howrah Bridge in Kolkata is the world's 6th longest cantilever bridge.", color: "#d35400" },
  { id: 338, cat: "CA 2026", title: "Global Biofuel", body: "2026: India became the lead producer in the Global Biofuel Alliance.", color: "#7f8c8d" },
  { id: 339, cat: "Awareness", title: "Public WiFi", body: "Never use public WiFi for banking. Hackers use 'Man-in-the-middle' attacks.", color: "#c0392b" },
  { id: 340, cat: "Quiz", title: "Deepest Point", body: "Mariana Trench in the Pacific Ocean is the deepest point on Earth.", color: "#16a085" },

  // DAY 35: Amendments & Agriculture
  { id: 341, cat: "Polity", title: "52nd Amendment", body: "Anti-Defection Law: Added the 10th Schedule to the Constitution (1985).", color: "#2980b9" },
  { id: 342, cat: "History", title: "Vijayanagara", body: "Founded by Harihara and Bukka in 1336 on the banks of Tungabhadra.", color: "#d35400" },
  { id: 343, cat: "Science", title: "Geothermal", body: "Energy derived from the internal heat of the Earth (e.g., Puga Valley).", color: "#9b59b6" },
  { id: 344, cat: "Economy", title: "FPI", body: "Foreign Portfolio Investment: Investing in financial assets (stocks/bonds) only.", color: "#2ecc71" },
  { id: 345, cat: "Geography", title: "Suez Canal", body: "Connects Mediterranean to Red Sea; shortcut for Europe-Asia trade.", color: "#27ae60" },
  { id: 346, cat: "Math", title: "Factorial", body: "5! = 5 x 4 x 3 x 2 x 1 = 120. Useful in probability and arrangements.", color: "#1abc9c" },
  { id: 347, cat: "Motivation", title: "The Dip", body: "Seth Godin: Everything worth doing has a 'Dip'—a hard part where most quit.", color: "#34495e" },
  { id: 348, cat: "CA 2026", title: "K-Ride", body: "Bengaluru Suburban Rail Project (K-Ride) phase 1 opened in April 2026.", color: "#f39c12" },
  { id: 349, cat: "Awareness", title: "Cookie Stealing", body: "2026 Hack: Stealing session cookies allows hackers to login without 2FA.", color: "#c0392b" },
  { id: 350, cat: "Quiz", title: "Oldest Planet", body: "Jupiter is the oldest planet, formed just after the Sun.", color: "#3498db" },

  // DAY 36: Parliament & Proteins
  { id: 351, cat: "Polity", title: "Article 249", body: "Power of Parliament to legislate on State List subjects in national interest.", color: "#3498db" },
  { id: 352, cat: "History", title: "Battle of Khanwa", body: "1527: Babur defeated Rana Sanga, solidifying Mughal rule in India.", color: "#e67e22" },
  { id: 353, cat: "Science", title: "Amino Acids", body: "The building blocks of proteins; there are 20 essential ones.", color: "#1abc9c" },
  { id: 354, cat: "Economy", title: "Insolvency", body: "IBC (Insolvency and Bankruptcy Code) helps resolve bad debts of firms.", color: "#27ae60" },
  { id: 355, cat: "Geography", title: "Equinox", body: "Occurs twice a year (Mar & Sept) when day and night are equal everywhere.", color: "#9b59b6" },
  { id: 356, cat: "Logic", title: "Dice", body: "Standard dice: opposite faces always add up to 7 (1-6, 2-5, 3-4).", color: "#8e44ad" },
  { id: 357, cat: "Did You Know?", title: "First Newspaper", body: "Hicky's Bengal Gazette (1780) was the first newspaper printed in India.", color: "#d35400" },
  { id: 358, cat: "CA 2026", title: "Global Gateway", body: "EU and India signed major infra connectivity pact under Global Gateway (2026).", color: "#2ecc71" },
  { id: 359, cat: "Awareness", title: "Cloud Storage", body: "Never store unencrypted passwords in simple text files on the Cloud.", color: "#c0392b" },
  { id: 360, cat: "Quiz", title: "Longest River", body: "The Nile is the longest river in the world (approx 6,650 km).", color: "#16a085" },

  // DAY 37: States & DNA
  { id: 361, cat: "Polity", title: "Article 371", body: "Special provisions for various states like Nagaland, Assam, and Manipur.", color: "#2980b9" },
  { id: 362, cat: "History", title: "Chola Dynasty", body: "Known for the world's most powerful navy and 'Chola Bronzes' (Nataraja).", color: "#d35400" },
  { id: 363, cat: "Science", title: "Mitosis", body: "Cell division resulting in two identical daughter cells for growth.", color: "#e74c3c" },
  { id: 364, cat: "Economy", title: "Indirect Tax", body: "GST is the biggest example; tax burden can be shifted to the consumer.", color: "#7f8c8d" },
  { id: 365, cat: "Geography", title: "Aravalli Range", body: "Oldest fold mountains in India; act as a barrier for the Thar Desert.", color: "#2ecc71" },
  { id: 366, cat: "Math", title: "Angle 180", body: "Straight angle is 180 degrees. At 6:00, clock hands make 180 degrees.", color: "#1abc9c" },
  { id: 367, cat: "Motivation", title: "Grit", body: "Angela Duckworth: Passion + Perseverance for long-term goals.", color: "#34495e" },
  { id: 368, cat: "CA 2026", title: "Lithium Mine", body: "India’s first large-scale lithium mining started in Jammu & Kashmir (2026).", color: "#16a085" },
  { id: 369, cat: "Awareness", title: "IoT Security", body: "2026: Always update the firmware of smart bulbs/speakers to avoid hacks.", color: "#c0392b" },
  { id: 370, cat: "Quiz", title: "Dead Sea", body: "The lowest point on Earth's land surface; so salty that fish cannot live.", color: "#3498db" },

  // DAY 38: Local Govt & Ecology
  { id: 371, cat: "Polity", title: "Article 243K", body: "State Election Commission: Responsible for Panchayat and Municipal polls.", color: "#3498db" },
  { id: 372, cat: "History", title: "Kabir", body: "Mystic poet who challenged rituals; taught equality of all humans.", color: "#e67e22" },
  { id: 373, cat: "Science", title: "Bioluminescence", body: "Light produced by living organisms (e.g., Fireflies, some Deep-sea fish).", color: "#16a085" },
  { id: 374, cat: "Economy", title: "Primary Market", body: "Where companies issue new stocks (IPO) for the first time.", color: "#c0392b" },
  { id: 375, cat: "Geography", title: "Western Disturbance", body: "Winter storms from Mediterranean; crucial for Rabi crops in North India.", color: "#9b59b6" },
  { id: 376, cat: "Logic", title: "Statements", body: "Critical Reasoning: Identifying assumptions vs. conclusions.", color: "#8e44ad" },
  { id: 377, cat: "Did You Know?", title: "First Train", body: "1853: First passenger train ran between Bori Bunder (Mumbai) and Thane.", color: "#d35400" },
  { id: 378, cat: "CA 2026", title: "Bhashini", body: "2026: India's AI translation tool 'Bhashini' now supports 22 languages live.", color: "#7f8c8d" },
  { id: 379, cat: "Awareness", title: "E-Rupee", body: "Offline CBDC (Digital Rupee) launched in 2026 for rural areas without net.", color: "#2ecc71" },
  { id: 380, cat: "Quiz", title: "Largest Desert", body: "Antarctic Desert is the largest; Sahara is the largest hot desert.", color: "#3498db" },

  // DAY 39: Rights & Planets
  { id: 381, cat: "Polity", title: "Article 352", body: "National Emergency: Proclaimed by President on grounds of War/Armed Revolt.", color: "#3498db" },
  { id: 382, cat: "History", title: "Sambhaji Maharaj", body: "Second Chhatrapati of Maratha Empire; scholar of Sanskrit and politics.", color: "#e67e22" },
  { id: 383, cat: "Science", title: "Supernova", body: "The massive explosion of a star at the end of its life cycle.", color: "#e74c3c" },
  { id: 384, cat: "Economy", title: "Bear Market", body: "A condition in which security prices fall 20% or more from recent highs.", color: "#2ecc71" },
  { id: 385, cat: "Geography", title: "Hormuz Strait", body: "World's most important oil chokepoint, connecting Persian Gulf to Oman.", color: "#9b59b6" },
  { id: 386, cat: "Motivation", title: "Dopamine", body: "The 'Reward' chemical. Social media scroll kills long-term motivation.", color: "#34495e" },
  { id: 387, cat: "Math", title: "Pythagorean", body: "Triplets: (3,4,5), (5,12,13), (8,15,17). Memorize for fast geometry.", color: "#1abc9c" },
  { id: 388, cat: "CA 2026", title: "Carbon-Capture", body: "India’s 1st industrial carbon-capture plant opened in Jamnagar (2026).", color: "#16a085" },
  { id: 389, cat: "Awareness", title: "Vishing", body: "Voice Phishing: Scammers call claiming to be your bank to get your OTP.", color: "#2ecc71" },
  { id: 390, cat: "Quiz", title: "Ring of Fire", body: "Zone in Pacific Ocean with most of world's earthquakes and volcanoes.", color: "#16a085" },

  // DAY 40: Revision & Governance
  { id: 391, cat: "Polity", title: "Adjournment Sine Die", body: "Terminating a sitting of Parliament for an indefinite period.", color: "#2980b9" },
  { id: 392, cat: "History", title: "British East India", body: "Founded in 1600; arrived in India in 1608 at Surat port.", color: "#d35400" },
  { id: 393, cat: "Science", title: "Newton's 2nd Law", body: "Force = Mass x Acceleration (F=ma).", color: "#f39c12" },
  { id: 394, cat: "Economy", title: "M3 Money", body: "Broad Money: M1 + Time deposits with the banking system.", color: "#7f8c8d" },
  { id: 395, cat: "Geography", title: "Yarlung Tsangpo", body: "The Tibetan name for the river Brahmaputra.", color: "#27ae60" },
  { id: 396, cat: "Logic", title: "Puzzles", body: "Floor-based and Box-based puzzles are common in competitive logic exams.", color: "#8e44ad" },
  { id: 397, cat: "Did You Know?", title: "Diamond Origin", body: "Until the 1700s, India was the world's only known source of diamonds.", color: "#7f8c8d" },
  { id: 398, cat: "CA 2026", title: "One-Nation-One-Id", body: "2026: APAAR ID for students integrated into all national degrees/results.", color: "#34495e" },
  { id: 399, cat: "Awareness", title: "Li-Ion Life", body: "Keep your phone battery between 20% and 80% to extend its total lifespan.", color: "#c0392b" },
  { id: 400, cat: "Quiz", title: "Smallest Ocean", body: "The Arctic Ocean is the smallest and shallowest of the five oceans.", color: "#16a085" },

// DAY 41: Authorities & Quantum
  { id: 401, cat: "Polity", title: "Article 76", body: "Attorney General: The highest law officer in India, appointed by the President.", color: "#3498db" },
  { id: 402, cat: "History", title: "Upanishads", body: "Philosophical texts (Vedanta) exploring the nature of Reality and Soul (Atman).", color: "#e67e22" },
  { id: 403, cat: "Science", title: "Quantum Entanglement", body: "Einstein called it 'Spooky action': Two particles stay linked regardless of distance.", color: "#1abc9c" },
  { id: 404, cat: "Economy", title: "Angel Tax", body: "2026: New exemptions for 'Deep-Tech' startups to boost Indian innovation.", color: "#2ecc71" },
  { id: 405, cat: "Geography", title: "Zoji La Tunnel", body: "2026: Asia's longest bi-directional tunnel provides all-weather connectivity to Ladakh.", color: "#9b59b6" },
  { id: 406, cat: "Logic", title: "Calendars", body: "An ordinary year has 1 odd day; a Leap year has 2 odd days.", color: "#8e44ad" },
  { id: 407, cat: "CA 2026", title: "DPDP Act", body: "Digital Personal Data Protection rules fully enforced across all Indian apps (2026).", color: "#34495e" },
  { id: 408, cat: "Motivation", title: "Active Recall", body: "Testing yourself instead of re-reading. It’s the #1 way to remember syllabus.", color: "#d35400" },
  { id: 409, cat: "Quiz", title: "First Census", body: "First non-synchronous census (1872) under Lord Mayo; first synchronous (1881).", color: "#16a085" },
  { id: 410, cat: "Awareness", title: "E-Sim", body: "2026 Trend: Phones moving to E-Sims only; no physical slot to prevent theft-tracking.", color: "#c0392b" },

  // DAY 42: Commissions & Culture
  { id: 411, cat: "Polity", title: "Article 338A", body: "National Commission for Scheduled Tribes (NCST): Separated from NCSC in 2003.", color: "#2980b9" },
  { id: 412, cat: "History", title: "Sangam Literature", body: "Earliest Tamil literature (Tolkappiyam, Silappadikaram) from South India.", color: "#d35400" },
  { id: 413, cat: "Science", title: "Hadron Collider", body: "CERN's 2026 upgrades are searching for 'Dark Matter' particles.", color: "#f1c40f" },
  { id: 414, cat: "Economy", title: "M-Pesa 2.0", body: "2026: India's UPI-lite system now allows offline payments up to 2000 INR.", color: "#27ae60" },
  { id: 415, cat: "Geography", title: "Humbold Current", body: "Cold ocean current off South America; linked to El Niño weather patterns.", color: "#9b59b6" },
  { id: 416, cat: "Math", title: "Speed Conversion", body: "To convert km/hr to m/s: Multiply by 5/18. Fast for train/car problems.", color: "#1abc9c" },
  { id: 417, cat: "Did You Know?", title: "Snakes & Ladders", body: "Originally called 'Moksha Patam' to teach kids about Karma and Rebirth.", color: "#7f8c8d" },
  { id: 118, cat: "CA 2026", title: "Bharat-GPU", body: "India's first indigenous high-performance GPU cluster launched for AI (2026).", color: "#34495e" },
  { id: 419, cat: "Awareness", title: "AI Deepfakes", body: "2026 Warning: Look for unnatural eye-blinking or blurred edges to spot fake videos.", color: "#c0392b" },
  { id: 420, cat: "Quiz", title: "Silicon Valley", body: "Bengaluru (Bangalore) is the Silicon Valley and IT capital of India.", color: "#16a085" },

  // DAY 43: Trade & Environment
  { id: 421, cat: "Polity", title: "Article 312", body: "Grants Rajya Sabha the power to create new All-India Services.", color: "#3498db" },
  { id: 422, cat: "History", title: "Sher Shah Suri", body: "Issued the 'Rupiya' (Silver coin) and built the Grand Trunk (GT) Road.", color: "#e67e22" },
  { id: 423, cat: "Science", title: "Cryogenics", body: "Study of materials at extremely low temperatures (below -150°C).", color: "#2ecc71" },
  { id: 424, cat: "Economy", title: "Tariff Barrier", body: "Taxes placed on imported goods to protect local Indian industries.", color: "#f39c12" },
  { id: 425, cat: "Geography", title: "Mariana Trench", body: "Challenger Deep is the deepest part (approx 11,000 meters) in the Pacific.", color: "#27ae60" },
  { id: 426, cat: "Logic", title: "Statement-Assump", body: "An assumption is the 'hidden' part of the logic that must be true.", color: "#8e44ad" },
  { id: 427, cat: "Math", title: "Cyclicity", body: "Powers of 2 repeat unit digits every 4 steps (2, 4, 8, 6).", color: "#1abc9c" },
  { id: 428, cat: "CA 2026", title: "PM Surya Ghar", body: "2026 Update: 10 Million Indian homes now powered by free solar rooftop electricity.", color: "#2980b9" },
  { id: 429, cat: "Awareness", title: "Passkeys", body: "2026: Biometric Passkeys have officially replaced passwords for Google/X logins.", color: "#2c3e50" },
  { id: 430, cat: "Quiz", title: "Tiger Census", body: "Every 4 years, India conducts its national tiger survey (NTCA).", color: "#d35400" },

  // DAY 44: Tribes & Battles
  { id: 431, cat: "Polity", title: "Article 148", body: "CAG (Comptroller and Auditor General): The Guardian of the Public Purse.", color: "#3498db" },
  { id: 432, cat: "History", title: "Battle of Khanwa", body: "1527: Babur defeated Rana Sanga, ending Rajput challenge to Mughals.", color: "#e67e22" },
  { id: 433, cat: "Science", title: "Viscosity", body: "Measure of a fluid's resistance to flow (e.g., honey is more viscous than water).", color: "#e74c3c" },
  { id: 434, cat: "Economy", title: "Secondary Sector", body: "Manufacturing/Industrial sector where raw materials are turned into goods.", color: "#3498db" },
  { id: 435, cat: "Geography", title: "Rohtang Pass", body: "Connects Kullu Valley with Lahaul and Spiti Valleys in Himachal.", color: "#2ecc71" },
  { id: 436, cat: "Motivation", title: "Parkinson's Law", body: "Work expands to fill the time available. Set shorter study deadlines.", color: "#34495e" },
  { id: 437, cat: "Did You Know?", title: "First Bridge", body: "The Bogibeel Bridge in Assam is India's longest rail-cum-road bridge.", color: "#d35400" },
  { id: 438, cat: "CA 2026", title: "Bharat-Gen", body: "India launched its own multi-modal GenAI model for 22 Indian languages (2026).", color: "#7f8c8d" },
  { id: 439, cat: "Awareness", title: "Cookie-Theft", body: "New 2026 malware steals browser 'sessions'. Never save login on public PCs.", color: "#c0392b" },
  { id: 440, cat: "Quiz", title: "Smallest Continent", body: "Australia is the smallest continent, often called the 'Island Continent'.", color: "#16a085" },

  // DAY 45: Finance & Flora
  { id: 441, cat: "Polity", title: "Article 266", body: "Consolidated Fund of India: All Govt revenues and loans are kept here.", color: "#2980b9" },
  { id: 442, cat: "History", title: "Kalinga War", body: "261 BCE: The bloodshed led Emperor Ashoka to embrace Buddhism/Ahimsa.", color: "#d35400" },
  { id: 443, cat: "Science", title: "Endocrine System", body: "Network of glands (Pituitary, Thyroid) that secrete hormones directly into blood.", color: "#9b59b6" },
  { id: 444, cat: "Economy", title: "M-Cap", body: "Market Capitalization: Share Price x Total Number of Shares.", color: "#2ecc71" },
  { id: 445, cat: "Geography", title: "Kyzyl Kum", body: "The 16th largest desert in the world, located in Central Asia.", color: "#27ae60" },
  { id: 446, cat: "Math", title: "Factorial 0", body: "0! is equal to 1. Crucial for Permutations/Combinations math.", color: "#1abc9c" },
  { id: 447, cat: "Motivation", title: "2-Minute Rule", body: "If a task takes less than 2 minutes, do it now. Don't add to your list.", color: "#34495e" },
  { id: 448, cat: "CA 2026", title: "Green Hydrogen", body: "2026: India's first Green Hydrogen bunkering terminal opened in Tuticorin.", color: "#f39c12" },
  { id: 449, cat: "Awareness", title: "Vishing", body: "Voice Phishing: Scammers use AI clones of voices to steal money over phone.", color: "#c0392b" },
  { id: 450, cat: "Quiz", title: "First Satellite", body: "Aryabhata (1975) was India's first satellite, launched by the Soviet Union.", color: "#3498db" },

  // DAY 46: States & Proteins
  { id: 451, cat: "Polity", title: "Article 200", body: "Powers of the Governor to give or withhold assent to State Bills.", color: "#3498db" },
  { id: 452, cat: "History", title: "Bhakti Saints", body: "Chaitanya Mahaprabhu popularized 'Sankirtan' (devotional songs) in Bengal.", color: "#e67e22" },
  { id: 453, cat: "Science", title: "Hemoglobin", body: "Iron-rich protein in RBCs that binds with oxygen and gives blood its red color.", color: "#1abc9c" },
  { id: 454, cat: "Economy", title: "Insolvency (IBC)", body: "The law to resolve bankrupt companies in a time-bound manner (270 days).", color: "#27ae60" },
  { id: 455, cat: "Geography", title: "Strait of Malacca", body: "Connects Indian Ocean to South China Sea; 25% of global trade passes here.", color: "#9b59b6" },
  { id: 456, cat: "Logic", title: "Syllogism 2", body: "If 'No A is B' and 'All B are C', then 'Some C are not A'.", color: "#8e44ad" },
  { id: 457, cat: "Did You Know?", title: "Diamonds", body: "Until 1726, India was the world's only producer of commercial diamonds.", color: "#d35400" },
  { id: 458, cat: "CA 2026", title: "Bhasha-Net", body: "2026: India's high-speed internet project specifically for regional languages.", color: "#2ecc71" },
  { id: 459, cat: "Awareness", title: "Phishing 2026", body: "New 'Quishing' (QR-Phishing): Never scan a QR code to 'receive' money.", color: "#c0392b" },
  { id: 460, cat: "Quiz", title: "Longest River", body: "The Nile (Africa) is the longest river; the Amazon has the most water volume.", color: "#16a085" },

  // DAY 47: Rights & Evolution
  { id: 461, cat: "Polity", title: "Article 32", body: "Right to Remedies. Ambedkar called it the 'Heart and Soul' of the Constitution.", color: "#2980b9" },
  { id: 462, cat: "History", title: "Vasco da Gama", body: "Arrived at Calicut (India) in 1498; opened the direct sea route from Europe.", color: "#d35400" },
  { id: 463, cat: "Science", title: "ATP", body: "Adenosine Triphosphate: The chemical fuel used by all living cells.", color: "#e74c3c" },
  { id: 464, cat: "Economy", title: "Fiscal Deficit", body: "Total Govt Expenditure - (Total Revenue - Borrowings).", color: "#7f8c8d" },
  { id: 465, cat: "Geography", title: "Aravalli Range", body: "Oldest fold mountains in India; highest peak is Guru Shikhar.", color: "#2ecc71" },
  { id: 466, cat: "Math", title: "Percentage Flip", body: "x% of y is the same as y% of x. (4% of 50 = 50% of 4 = 2).", color: "#1abc9c" },
  { id: 467, cat: "Motivation", title: "Zeigarnik Effect", body: "Our brain hates unfinished work. Just start for 5 mins to break resistance.", color: "#34495e" },
  { id: 468, cat: "CA 2026", title: "Digital Rupee", body: "2026 Update: 50% of all P2P transactions in India now use CBDC (e-Rupee).", color: "#16a085" },
  { id: 469, cat: "Awareness", title: "Smart-Device Security", body: "2026: IoT devices (Fridge/AC) are common hacker targets. Use separate Wi-Fi.", color: "#c0392b" },
  { id: 470, cat: "Quiz", title: "Highest Waterfall", body: "Angel Falls (Venezuela) is the highest uninterrupted waterfall on Earth.", color: "#3498db" },

  // DAY 48: Duties & Climate
  { id: 471, cat: "Polity", title: "Article 51A", body: "Lists 11 Fundamental Duties; added by 42nd Amendment in 1976.", color: "#3498db" },
  { id: 472, cat: "History", title: "Battle of Buxar", body: "1764: British victory over Mir Qasim, Shuja-ud-Daula, and Shah Alam II.", color: "#e67e22" },
  { id: 473, cat: "Science", title: "Ozone Layer", body: "Found in Stratosphere; shields us from UV rays that cause skin cancer.", color: "#16a085" },
  { id: 474, cat: "Economy", title: "M-3 Money", body: "Broad Money: Includes M-1 + time deposits with the banking system.", color: "#c0392b" },
  { id: 475, cat: "Geography", title: "Tropic of Cancer", body: "Passes through 8 states in India (GJ, RJ, MP, CH, JH, WB, TR, MZ).", color: "#9b59b6" },
  { id: 476, cat: "Logic", title: "Analogy", body: "Identifying relationships: 'Heart : Blood :: Pump : ?' (Answer: Water).", color: "#8e44ad" },
  { id: 477, cat: "Did You Know?", title: "Sushruta", body: "The Indian 'Father of Surgery' who practiced rhinoplasty 2,600 years ago.", color: "#d35400" },
  { id: 478, cat: "CA 2026", title: "Project Kusha", body: "India's own S-400-like air defense system to be fully operational in 2026.", color: "#7f8c8d" },
  { id: 479, cat: "Awareness", title: "AI-Safety Act", body: "2026: Law mandates all AI-generated content must carry a visible watermark.", color: "#2ecc71" },
  { id: 480, cat: "Quiz", title: "Iron Man", body: "Sardar Vallabhbhai Patel, the first Home Minister of independent India.", color: "#3498db" },

  // DAY 49: Rights & Biology
  { id: 481, cat: "Polity", title: "Article 21A", body: "Right to Education: Free and compulsory for children aged 6 to 14.", color: "#3498db" },
  { id: 482, cat: "History", title: "Jain Tirthankaras", body: "Lord Mahavira was the 24th and last Tirthankara of Jainism.", color: "#e67e22" },
  { id: 483, cat: "Science", title: "White Blood Cells", body: "The soldiers of the immune system that fight bacteria and viruses.", color: "#e74c3c" },
  { id: 484, cat: "Economy", title: "Bear Market", body: "When stock prices fall 20% or more from their recent highs.", color: "#2ecc71" },
  { id: 485, cat: "Geography", title: "Standard Time", body: "IST is 5 hours and 30 minutes ahead of Greenwich Mean Time (GMT).", color: "#9b59b6" },
  { id: 486, cat: "Motivation", title: "Dopamine Detox", body: "Avoiding short-term stimulation (social media) to reset focus and drive.", color: "#34495e" },
  { id: 487, cat: "Math", title: "Prime Sum", body: "The sum of the first five prime numbers (2+3+5+7+11) is 28.", color: "#1abc9c" },
  { id: 488, cat: "CA 2026", title: "Semicon India", body: "2026: Tata and Micron semiconductor plants in Gujarat started global exports.", color: "#16a085" },
  { id: 489, cat: "Awareness", title: "Blue Light", body: "Using 'Night Shift' mode helps Melatonin production for better sleep.", color: "#2ecc71" },
  { id: 490, cat: "Quiz", title: "Oldest Range", body: "The Aravalli mountains are the oldest fold mountains in India.", color: "#16a085" },

  // DAY 50: Revision & Governance
  { id: 491, cat: "Polity", title: "Joint Sitting", body: "Presided over by the Speaker of Lok Sabha (Article 108).", color: "#2980b9" },
  { id: 492, cat: "History", title: "British East India", body: "Received Charter from Queen Elizabeth I in 1600 to trade in the East.", color: "#d35400" },
  { id: 493, cat: "Science", title: "Speed of Light", body: "Exactly 299,792,458 meters per second in a vacuum.", color: "#f39c12" },
  { id: 494, cat: "Economy", title: "Tertiary Sector", body: "Service sector (Banking, IT, Tourism) that supports primary/secondary sectors.", color: "#7f8c8d" },
  { id: 495, cat: "Geography", title: "Godavari River", body: "Known as 'Dakshin Ganga', it is the longest river in South India.", color: "#27ae60" },
  { id: 496, cat: "Logic", title: "Mirror Image", body: "Horizontal flip where Left becomes Right and Right becomes Left.", color: "#8e44ad" },
  { id: 497, cat: "Did You Know?", title: "Zero Discovery", body: "The concept of Zero was given to the world by Indian scholar Brahmagupta.", color: "#7f8c8d" },
  { id: 498, cat: "CA 2026", title: "Cyber-Security", body: "India ranked Top 5 globally in Cyber-Security Readiness in 2026.", color: "#34495e" },
  { id: 499, cat: "Awareness", title: "E-Waste 2026", body: "India's 2026 law: Companies must 'Buy Back' old gadgets for recycling.", color: "#c0392b" },
  { id: 500, cat: "Quiz", title: "Largest Ocean", body: "The Pacific Ocean covers more than one-third of the Earth's surface.", color: "#16a085" },

// DAY 51: Emergencies & Space
  { id: 501, cat: "Polity", title: "Article 352", body: "National Emergency: Proclaimed by President on grounds of war or armed rebellion.", color: "#3498db" },
  { id: 502, cat: "History", title: "Raja Ram Mohan Roy", body: "Known as the 'Father of Indian Renaissance'; founded Brahmo Samaj in 1828.", color: "#e67e22" },
  { id: 503, cat: "Science", title: "Gaganyaan 2026", body: "India's first manned space mission aiming to send 3 astronauts to Low Earth Orbit.", color: "#1abc9c" },
  { id: 504, cat: "Economy", title: "Gig Economy", body: "2026 Update: New social security laws passed for platform workers (Swiggy, Zomato).", color: "#2ecc71" },
  { id: 505, cat: "Geography", title: "Rohtang Pass", body: "Connects Kullu Valley with Lahaul and Spiti Valleys in Himachal Pradesh.", color: "#9b59b6" },
  { id: 506, cat: "Logic", title: "Calendars", body: "Odd Days: The number of days more than a complete week (e.g., 10 days = 3 odd days).", color: "#8e44ad" },
  { id: 507, cat: "CA 2026", title: "National Quantum", body: "India successfully developed its first 50-qubit quantum computer in 2026.", color: "#34495e" },
  { id: 508, cat: "Motivation", title: "Spaced Repetition", body: "Reviewing information at increasing intervals to move it to long-term memory.", color: "#d35400" },
  { id: 509, cat: "Quiz", title: "First Census", body: "The first complete/synchronous census of India was conducted in 1881.", color: "#16a085" },
  { id: 510, cat: "Awareness", title: "Phishing 2026", body: "Never click 'Account Verification' links via SMS; banks never ask for passwords.", color: "#c0392b" },

  // DAY 52: Finance & Freedom
  { id: 511, cat: "Polity", title: "Article 360", body: "Financial Emergency: It has never been proclaimed in India to date.", color: "#2980b9" },
  { id: 512, cat: "History", title: "Subhash Chandra Bose", body: "Founded the Forward Bloc and led the Indian National Army (INA) in 1943.", color: "#d35400" },
  { id: 513, cat: "Science", title: "Mangalyaan 2", body: "2026: ISRO launched Mars Orbiter Mission-2 with a lander and a rover.", color: "#f1c40f" },
  { id: 114, cat: "Economy", title: "FinTech 2026", body: "India's UPI-lite now supports offline transactions up to 5000 INR (2026).", color: "#27ae60" },
  { id: 515, cat: "Geography", title: "Karakoram Pass", body: "Located on the boundary of Ladakh (India) and Xinjiang (China).", color: "#9b59b6" },
  { id: 516, cat: "Math", title: "Unit Digit 5", body: "Any power of a number ending in 5 will always result in a unit digit of 5.", color: "#1abc9c" },
  { id: 517, cat: "Did You Know?", title: "Shampoo", body: "Derived from 'Champo' (Sanskrit); the concept originated in Ancient India.", color: "#7f8c8d" },
  { id: 518, cat: "CA 2026", title: "Bhavasagara", body: "India's 1st National Repository for Deep-Sea Fauna, designated in Kochi (2026).", color: "#34495e" },
  { id: 519, cat: "Awareness", title: "SIM Swap", body: "If your signal disappears suddenly, contact your bank immediately to prevent fraud.", color: "#c0392b" },
  { id: 520, cat: "Quiz", title: "Silicon Valley", body: "Bengaluru is widely known as the Silicon Valley of India.", color: "#16a085" },

  // DAY 53: Rights & Resources
  { id: 521, cat: "Polity", title: "Article 32", body: "Right to Remedies: The 'Heart and Soul' of the Constitution (Supreme Court Writs).", color: "#3498db" },
  { id: 522, cat: "History", title: "Annie Besant", body: "The first woman President of the Indian National Congress (INC).", color: "#e67e22" },
  { id: 523, cat: "Science", title: "Geothermal", body: "2026: Puga Valley (Ladakh) plant became India's first operational geothermal unit.", color: "#2ecc71" },
  { id: 524, cat: "Economy", title: "G-Secs", body: "Government Securities: Debt instruments used by the Govt to borrow money.", color: "#f39c12" },
  { id: 525, cat: "Geography", title: "Bomdi La", body: "Strategic pass in Arunachal Pradesh connecting India with Lhasa, Tibet.", color: "#27ae60" },
  { id: 526, cat: "Logic", title: "Venn Diagrams", body: "Used to show logical relationships between sets of data visually.", color: "#8e44ad" },
  { id: 527, cat: "Math", title: "Prime Sum", body: "The sum of the first five prime numbers (2+3+5+7+11) is 28.", color: "#1abc9c" },
  { id: 528, cat: "CA 2026", title: "SDG Dashboard", body: "MoSPI launched the 'India SDG Dashboard 2026' to track national targets.", color: "#2980b9" },
  { id: 529, cat: "Awareness", title: "Dark Mode", body: "Reduces blue light exposure, helping maintain your body's Melatonin levels.", color: "#2c3e50" },
  { id: 530, cat: "Quiz", title: "Tiger State", body: "Madhya Pradesh holds the record for the highest tiger population in India.", color: "#d35400" },

  // DAY 54: Bodies & Battles
  { id: 531, cat: "Polity", title: "Article 315", body: "Constitutional provision for the Union and State Public Service Commissions.", color: "#3498db" },
  { id: 532, cat: "History", title: "Dadabhai Naoroji", body: "The 'Grand Old Man of India'; authored 'Poverty and Un-British Rule in India'.", color: "#e67e22" },
  { id: 533, cat: "Science", title: "Mitochondria", body: "The powerhouse of the cell; produces ATP energy for cellular functions.", color: "#e74c3c" },
  { id: 534, cat: "Economy", title: "Blue Revolution", body: "Refers to the significant growth in fish and aquaculture production.", color: "#3498db" },
  { id: 535, cat: "Geography", title: "Western Ghats", body: "Older than the Himalayas; a UNESCO global biodiversity hotspot.", color: "#2ecc71" },
  { id: 536, cat: "Motivation", title: "Atomic Habits", body: "James Clear: Getting 1% better every day makes you 37x better in a year.", color: "#34495e" },
  { id: 537, cat: "Did You Know?", title: "Chess Origin", body: "Chess originated in India, known originally as 'Chaturanga'.", color: "#d35400" },
  { id: 538, cat: "CA 2026", title: "LUPEX", body: "ISRO-JAXA joint mission (2026) to explore water ice on the Moon's South Pole.", color: "#7f8c8d" },
  { id: 539, cat: "Awareness", title: "VPN Security", body: "Virtual Private Networks encrypt your data, but free ones may sell your history.", color: "#c0392b" },
  { id: 540, cat: "Quiz", title: "Largest Delta", body: "The Ganga-Brahmaputra Delta (Sundarbans) is the world's largest delta.", color: "#16a085" },

  // DAY 55: Amendments & Energy
  { id: 541, cat: "Polity", title: "42nd Amendment", body: "Known as the 'Mini Constitution'; added 'Socialist' and 'Secular' to the Preamble.", color: "#2980b9" },
  { id: 542, cat: "History", title: "Mohenjo-daro", body: "Means 'Mound of the Dead'; famous for its planned streets and Great Bath.", color: "#d35400" },
  { id: 543, cat: "Science", title: "Escape Velocity", body: "The speed (11.2 km/s) required for an object to break free from Earth's gravity.", color: "#9b59b6" },
  { id: 544, cat: "Economy", title: "Direct Tax", body: "Taxes paid by the person on whom they are levied (e.g., Income Tax).", color: "#2ecc71" },
  { id: 545, cat: "Geography", title: "Kanchenjunga", body: "The highest mountain peak located entirely within Indian territory.", color: "#27ae60" },
  { id: 546, cat: "Math", title: "Percentage Flip", body: "x% of y = y% of x. (e.g., 4% of 50 is easier as 50% of 4 = 2).", color: "#1abc9c" },
  { id: 547, cat: "Motivation", title: "80/20 Rule", body: "Pareto Principle: 20% of your focused study time produces 80% of your results.", color: "#34495e" },
  { id: 548, cat: "CA 2026", title: "Bharat-GPU", body: "India launched its 1st high-performance GPU cluster for AI development (2026).", color: "#f39c12" },
  { id: 549, cat: "Awareness", title: "Incognito", body: "Incognito mode hides history on your device but NOT from your ISP or Admin.", color: "#c0392b" },
  { id: 550, cat: "Quiz", title: "First Citizen", body: "The President of India is the symbolic First Citizen of the nation.", color: "#3498db" },

  // DAY 56: Parliament & Particles
  { id: 551, cat: "Polity", title: "Article 110", body: "Defines Money Bills. The Speaker of Lok Sabha decides if a bill is a Money Bill.", color: "#3498db" },
  { id: 552, cat: "History", title: "Battle of Plassey", body: "1757: Robert Clive defeated the Nawab of Bengal, starting British rule.", color: "#e67e22" },
  { id: 553, cat: "Science", title: "Isotopes", body: "Atoms of the same element with same atomic number but different mass numbers.", color: "#1abc9c" },
  { id: 554, cat: "Economy", title: "FDI", body: "Foreign Direct Investment: Investment into Indian businesses by foreigners.", color: "#27ae60" },
  { id: 555, cat: "Geography", title: "Palk Strait", body: "The narrow sea that separates India (Tamil Nadu) from Sri Lanka.", color: "#9b59b6" },
  { id: 556, cat: "Logic", title: "Number Series", body: "Always check for Square, Cube, or Prime number gaps in sequence puzzles.", color: "#8e44ad" },
  { id: 557, cat: "Did You Know?", title: "Shakuntala Devi", body: "Known as the 'Human Computer'; could multiply 13-digit numbers in 28 seconds.", color: "#d35400" },
  { id: 558, cat: "CA 2026", title: "Indo-USA Pact", body: "2026: Major drone and jet engine technology transfer agreement signed.", color: "#2ecc71" },
  { id: 559, cat: "Awareness", title: "2FA", body: "Two-Factor Authentication: The best defense against social media hacking.", color: "#c0392b" },
  { id: 560, cat: "Quiz", title: "Smallest State", body: "Goa is the smallest state in India by total land area.", color: "#16a085" },

  // DAY 57: Local Govt & Biology
  { id: 561, cat: "Polity", title: "73rd Amendment", body: "Gave constitutional status to Panchayati Raj (Rural Local Bodies).", color: "#2980b9" },
  { id: 562, cat: "History", title: "Harsha Charita", body: "Biography of King Harshavardhana, written by his court poet Banabhatta.", color: "#d35400" },
  { id: 563, cat: "Science", title: "Red Blood Cells", body: "Carry oxygen via Hemoglobin; RBCs lack a nucleus to save space.", color: "#e74c3c" },
  { id: 564, cat: "Economy", title: "Direct Tax", body: "Taxes paid by the person on whom they are levied (e.g., Income Tax).", color: "#7f8c8d" },
  { id: 565, cat: "Geography", title: "Majuli Island", body: "Located in the Brahmaputra, Assam; the world's largest river island.", color: "#2ecc71" },
  { id: 566, cat: "Math", title: "Speed Conversion", body: "To convert km/hr to m/s: Multiply by 5/18. (e.g., 90 km/hr = 25 m/s).", color: "#1abc9c" },
  { id: 567, cat: "Motivation", title: "Growth Mindset", body: "The belief that persistence and effort can lead to higher intelligence.", color: "#34495e" },
  { id: 568, cat: "CA 2026", title: "Solar Power", body: "India targets 500 GW of non-fossil fuel energy capacity by 2030.", color: "#16a085" },
  { id: 569, cat: "Awareness", title: "Post-Naxal Dev.", body: "2026 Focus: Fast-tracking schools and hospitals in former Red Corridor districts.", color: "#c0392b" },
  { id: 570, cat: "Quiz", title: "Yamuna River", body: "The largest and most important tributary of the River Ganga.", color: "#3498db" },

  // DAY 58: Duties & Climate
  { id: 571, cat: "Polity", title: "Article 51A", body: "Fundamental Duties (11 total). Inspired by the USSR constitution.", color: "#3498db" },
  { id: 572, cat: "History", title: "Jallianwala Bagh", body: "1919: General Dyer ordered firing on a peaceful crowd in Amritsar.", color: "#e67e22" },
  { id: 573, cat: "Science", title: "Ozone Layer", body: "Found in Stratosphere; shields the Earth from harmful solar UV rays.", color: "#16a085" },
  { id: 574, cat: "Economy", title: "Inflation (CPI)", body: "Consumer Price Index: Measures price changes from the buyer's view.", color: "#c0392b" },
  { id: 575, cat: "Geography", title: "Great Circles", body: "The shortest path between two points on a sphere (Crucial for pilots).", color: "#9b59b6" },
  { id: 576, cat: "Logic", title: "Analogy", body: "Solving logic pairs based on shared properties. (e.g., Cat:Kitten :: Dog:Puppy).", color: "#8e44ad" },
  { id: 577, cat: "Did You Know?", title: "Nalanda", body: "First residential university in the world, founded in 5th Century AD.", color: "#d35400" },
  { id: 578, cat: "CA 2026", title: "Antariksh Startups", body: "India's space venture capital fund began investing in deep-tech startups in 2026.", color: "#7f8c8d" },
  { id: 579, cat: "Awareness", title: "QR Fraud", body: "Reminder: You scan a QR code to SEND money, never to RECEIVE it.", color: "#2ecc71" },
  { id: 580, cat: "Quiz", title: "National Anthem", body: "Written by Rabindranath Tagore; first sung in 1911 Calcutta session.", color: "#3498db" },

  // DAY 59: Rights & Cells
  { id: 581, cat: "Polity", title: "Article 368", body: "Grants Parliament the power to amend the Constitution.", color: "#3498db" },
  { id: 582, cat: "History", title: "Indus Dockyard", body: "Lothal (Gujarat) had the world's first artificial tidal dockyard.", color: "#e67e22" },
  { id: 583, cat: "Science", title: "White Blood Cells", body: "The soldiers of the immune system that protect the body from infections.", color: "#e74c3c" },
  { id: 584, cat: "Economy", title: "Capital Market", body: "Where long-term financial instruments (shares/bonds) are traded.", color: "#2ecc71" },
  { id: 585, cat: "Geography", title: "Sundarbans", body: "World's largest delta; home to the Royal Bengal Tiger.", color: "#9b59b6" },
  { id: 586, cat: "Motivation", title: "Flow State", body: "Being fully immersed and energized in what you are doing.", color: "#34495e" },
  { id: 587, cat: "Math", title: "Pythagorean", body: "Triplets: (3,4,5), (5,12,13), (8,15,17). Memorize for fast geometry.", color: "#1abc9c" },
  { id: 588, cat: "CA 2026", title: "Green Bonds", body: "2026: India raised $10B via Green Bonds for solar/wind infra.", color: "#16a085" },
  { id: 589, cat: "Awareness", title: "Phishing 2026", body: "New 'Quishing' (QR-Phishing): Scammers use fake QRs in public areas.", color: "#2ecc71" },
  { id: 590, cat: "Quiz", title: "Golden Fiber", body: "Jute is known as the 'Golden Fiber' for its high economic value.", color: "#16a085" },

  // DAY 60: Revision & Governance
  { id: 591, cat: "Polity", title: "NITI Aayog", body: "Replaced Planning Commission (2015); the PM is the ex-officio Chairman.", color: "#2980b9" },
  { id: 592, cat: "History", title: "Battle of Haldighati", body: "1576: Fought between Maharana Pratap and the Mughal forces of Akbar.", color: "#d35400" },
  { id: 593, cat: "Science", title: "Newton's 3rd Law", body: "Every action has an equal and opposite reaction (How rockets launch).", color: "#f39c12" },
  { id: 594, cat: "Economy", title: "Repo Rate", body: "The interest rate at which RBI lends money to commercial banks.", color: "#7f8c8d" },
  { id: 595, cat: "Geography", title: "Aravalli Range", body: "Oldest fold mountain range in India; act as a barrier for the Thar desert.", color: "#27ae60" },
  { id: 596, cat: "Logic", title: "Series Logic", body: "Check for Square/Cube diffs or Prime gaps to find the next item.", color: "#8e44ad" },
  { id: 597, cat: "Did You Know?", title: "Number System", body: "Modern decimal system and place value were developed in Ancient India.", color: "#7f8c8d" },
  { id: 598, cat: "CA 2026", title: "Digital Personal Data", body: "2026: New rules require apps to allow users to delete all personal data.", color: "#34495e" },
  { id: 599, cat: "Awareness", title: "Post-Naxal Dev.", body: "Final 2026 focus: Integration of remote tribal areas into the mainstream.", color: "#c0392b" },
  { id: 600, cat: "Quiz", title: "Largest Ocean", body: "The Pacific Ocean covers more than one-third of the entire Earth.", color: "#16a085" }
];
```javascript
// This line is CRITICAL for the Web Version to work
window.gyanDatabase = gyanDatabase;
